//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAppBarLayoutPlugin\src\main\java\com\ashera\appbarlayout\AppBarLayoutImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AppBarLayoutImpl")
#ifdef RESTRICT_AppBarLayoutImpl
#define INCLUDE_ALL_AppBarLayoutImpl 0
#else
#define INCLUDE_ALL_AppBarLayoutImpl 1
#endif
#undef RESTRICT_AppBarLayoutImpl

#if !defined (ASAppBarLayoutImpl_) && (INCLUDE_ALL_AppBarLayoutImpl || defined(INCLUDE_ASAppBarLayoutImpl))
#define ASAppBarLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASAppBarLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl)

inline NSString *ASAppBarLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASAppBarLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASAppBarLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASAppBarLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASAppBarLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASAppBarLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASAppBarLayoutImpl_init(ASAppBarLayoutImpl *self);

FOUNDATION_EXPORT ASAppBarLayoutImpl *new_ASAppBarLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl *create_ASAppBarLayoutImpl_init(void);

FOUNDATION_EXPORT void ASAppBarLayoutImpl_initWithNSString_(ASAppBarLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASAppBarLayoutImpl *new_ASAppBarLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl *create_ASAppBarLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASAppBarLayoutImpl_initWithNSString_withNSString_(ASAppBarLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASAppBarLayoutImpl *new_ASAppBarLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl *create_ASAppBarLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutImpl)

@compatibility_alias ComAsheraAppbarlayoutAppBarLayoutImpl ASAppBarLayoutImpl;


#endif

#if !defined (ASAppBarLayoutImpl_Layout_scrollFlags_) && (INCLUDE_ALL_AppBarLayoutImpl || defined(INCLUDE_ASAppBarLayoutImpl_Layout_scrollFlags))
#define ASAppBarLayoutImpl_Layout_scrollFlags_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASAppBarLayoutImpl_Layout_scrollFlags : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl_Layout_scrollFlags)

FOUNDATION_EXPORT void ASAppBarLayoutImpl_Layout_scrollFlags_init(ASAppBarLayoutImpl_Layout_scrollFlags *self);

FOUNDATION_EXPORT ASAppBarLayoutImpl_Layout_scrollFlags *new_ASAppBarLayoutImpl_Layout_scrollFlags_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl_Layout_scrollFlags *create_ASAppBarLayoutImpl_Layout_scrollFlags_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutImpl_Layout_scrollFlags)


#endif

#if !defined (ASAppBarLayoutImpl_AppBarLayoutExt_) && (INCLUDE_ALL_AppBarLayoutImpl || defined(INCLUDE_ASAppBarLayoutImpl_AppBarLayoutExt))
#define ASAppBarLayoutImpl_AppBarLayoutExt_

#define RESTRICT_AppBarLayout 1
#define INCLUDE_ASAppBarLayout 1
#include "AppBarLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASAppBarLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASAppBarLayoutImpl_AppBarLayoutExt : ASAppBarLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl_AppBarLayoutExt)

FOUNDATION_EXPORT void ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutExt *self, ASAppBarLayoutImpl *outer$);

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutExt *new_ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutExt *create_ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutImpl_AppBarLayoutExt)


#endif

#pragma pop_macro("INCLUDE_ALL_AppBarLayoutImpl")
