//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAppBarLayoutPlugin\src\main\java\com\ashera\appbarlayout\AppBarLayoutPlugin.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "AppBarLayout.h"
#include "AppBarLayoutImpl.h"
#include "AppBarLayoutPlugin.h"
#include "IBehavior.h"
#include "J2ObjC_source.h"
#include "WidgetFactory.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASAppBarLayoutPlugin_1 : NSObject < ASIBehavior >

- (instancetype)init;

- (id)newInstance OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutPlugin_1)

__attribute__((unused)) static void ASAppBarLayoutPlugin_1_init(ASAppBarLayoutPlugin_1 *self);

__attribute__((unused)) static ASAppBarLayoutPlugin_1 *new_ASAppBarLayoutPlugin_1_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASAppBarLayoutPlugin_1 *create_ASAppBarLayoutPlugin_1_init(void);


@implementation ASAppBarLayoutPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASAppBarLayoutPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASAppBarLayoutPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASAppBarLayoutPlugin = { "AppBarLayoutPlugin", "com.ashera.appbarlayout", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASAppBarLayoutPlugin;
}

@end

void ASAppBarLayoutPlugin_init(ASAppBarLayoutPlugin *self) {
  NSObject_init(self);
}

ASAppBarLayoutPlugin *new_ASAppBarLayoutPlugin_init() {
  J2OBJC_NEW_IMPL(ASAppBarLayoutPlugin, init)
}

ASAppBarLayoutPlugin *create_ASAppBarLayoutPlugin_init() {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutPlugin, init)
}

void ASAppBarLayoutPlugin_initPlugin() {
  ASAppBarLayoutPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ASAppBarLayoutImpl_init());
  ASWidgetFactory_registerBehaviorWithNSString_withASIBehavior_(@"@string/appbar_scrolling_view_behavior", new_ASAppBarLayoutPlugin_1_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAppBarLayoutPlugin)

J2OBJC_NAME_MAPPING(ASAppBarLayoutPlugin, "com.ashera.appbarlayout", "AS")

@implementation ASAppBarLayoutPlugin_1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASAppBarLayoutPlugin_1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id)newInstance {
  return new_ASAppBarLayout_ScrollingViewBehavior_init();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(newInstance);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASAppBarLayoutPlugin;", "initPlugin" };
  static const J2ObjcClassInfo _ASAppBarLayoutPlugin_1 = { "", "com.ashera.appbarlayout", ptrTable, methods, NULL, 7, 0x8000, 2, 0, 0, -1, 1, -1, -1 };
  return &_ASAppBarLayoutPlugin_1;
}

@end

void ASAppBarLayoutPlugin_1_init(ASAppBarLayoutPlugin_1 *self) {
  NSObject_init(self);
}

ASAppBarLayoutPlugin_1 *new_ASAppBarLayoutPlugin_1_init() {
  J2OBJC_NEW_IMPL(ASAppBarLayoutPlugin_1, init)
}

ASAppBarLayoutPlugin_1 *create_ASAppBarLayoutPlugin_1_init() {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutPlugin_1, init)
}
