//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAppBarLayoutPlugin\src\main\java\com\google\android\material\appbar\AppBarLayout.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AppBarLayout")
#ifdef RESTRICT_AppBarLayout
#define INCLUDE_ALL_AppBarLayout 0
#else
#define INCLUDE_ALL_AppBarLayout 1
#endif
#undef RESTRICT_AppBarLayout
#ifdef INCLUDE_ASAppBarLayout_Behavior
#define INCLUDE_ASAppBarLayout_BaseBehavior 1
#endif
#ifdef INCLUDE_ASAppBarLayout_OnOffsetChangedListener
#define INCLUDE_ASAppBarLayout_BaseOnOffsetChangedListener 1
#endif

#if !defined (ASAppBarLayout_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout))
#define ASAppBarLayout_

#define RESTRICT_LinearLayout 1
#define INCLUDE_ADLinearLayout 1
#include "LinearLayout.h"

#define RESTRICT_CoordinatorLayout 1
#define INCLUDE_ADXCoordinatorLayout_AttachedBehavior 1
#include "CoordinatorLayout.h"

@class ADContext;
@class ADDrawable;
@class ADView;
@class ADViewGroup_LayoutParams;
@class ADXCoordinatorLayout_Behavior;
@class ASAppBarLayout_LayoutParams;
@protocol ASAppBarLayout_BaseOnOffsetChangedListener;
@protocol ASAppBarLayout_LiftOnScrollListener;
@protocol ASAppBarLayout_OnOffsetChangedListener;

@interface ASAppBarLayout : ADLinearLayout < ADXCoordinatorLayout_AttachedBehavior >

#pragma mark Public

- (instancetype)init;

- (void)addLiftOnScrollListenerWithASAppBarLayout_LiftOnScrollListener:(id<ASAppBarLayout_LiftOnScrollListener>)liftOnScrollListener;

- (void)addOnOffsetChangedListenerWithASAppBarLayout_BaseOnOffsetChangedListener:(id<ASAppBarLayout_BaseOnOffsetChangedListener>)listener;

- (void)addOnOffsetChangedListenerWithASAppBarLayout_OnOffsetChangedListener:(id<ASAppBarLayout_OnOffsetChangedListener>)listener;

- (void)clearLiftOnScrollListener;

- (ADXCoordinatorLayout_Behavior *)getBehavior;

- (jint)getMinimumHeightForVisibleOverlappingContent;

- (ADDrawable *)getStateListAnimator;

- (jint)getTotalScrollRange;

- (jboolean)isLifted;

- (jboolean)isLiftOnScroll;

- (jboolean)removeLiftOnScrollListenerWithASAppBarLayout_LiftOnScrollListener:(id<ASAppBarLayout_LiftOnScrollListener>)liftOnScrollListener;

- (void)removeOnOffsetChangedListenerWithASAppBarLayout_BaseOnOffsetChangedListener:(id<ASAppBarLayout_BaseOnOffsetChangedListener>)listener;

- (void)removeOnOffsetChangedListenerWithASAppBarLayout_OnOffsetChangedListener:(id<ASAppBarLayout_OnOffsetChangedListener>)listener;

- (void)setExpandedWithBoolean:(jboolean)expanded;

- (void)setExpandedWithBoolean:(jboolean)expanded
                   withBoolean:(jboolean)animate;

- (jboolean)setLiftableWithBoolean:(jboolean)liftable;

- (void)setLiftableOverrideEnabledWithBoolean:(jboolean)enabled;

- (void)setLiftOnScrollWithBoolean:(jboolean)liftOnScroll;

- (void)setOrientationWithInt:(jint)orientation;

#pragma mark Protected

- (jboolean)checkLayoutParamsWithADViewGroup_LayoutParams:(ADViewGroup_LayoutParams *)p;

- (ASAppBarLayout_LayoutParams *)generateDefaultLayoutParams;

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

#pragma mark Package-Private

- (jint)getDownNestedPreScrollRange;

- (jint)getDownNestedScrollRange;

- (jint)getPendingAction;

- (jint)getTopInset;

- (jint)getUpNestedPreScrollRange;

- (jboolean)hasChildWithInterpolator;

- (jboolean)hasScrollableChildren;

- (void)onOffsetChangedWithInt:(jint)offset;

- (void)resetPendingAction;

- (jboolean)setLiftedStateWithBoolean:(jboolean)lifted;

- (jboolean)setLiftedStateWithBoolean:(jboolean)lifted
                          withBoolean:(jboolean)force;

- (jboolean)shouldLiftWithADView:(ADView *)defaultScrollingView;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithADContext:(ADContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout)

inline jint ASAppBarLayout_get_PENDING_ACTION_NONE(void);
#define ASAppBarLayout_PENDING_ACTION_NONE 0
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout, PENDING_ACTION_NONE, jint)

inline jint ASAppBarLayout_get_PENDING_ACTION_EXPANDED(void);
#define ASAppBarLayout_PENDING_ACTION_EXPANDED 1
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout, PENDING_ACTION_EXPANDED, jint)

inline jint ASAppBarLayout_get_PENDING_ACTION_COLLAPSED(void);
#define ASAppBarLayout_PENDING_ACTION_COLLAPSED 2
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout, PENDING_ACTION_COLLAPSED, jint)

inline jint ASAppBarLayout_get_PENDING_ACTION_ANIMATE_ENABLED(void);
#define ASAppBarLayout_PENDING_ACTION_ANIMATE_ENABLED 4
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout, PENDING_ACTION_ANIMATE_ENABLED, jint)

inline jint ASAppBarLayout_get_PENDING_ACTION_FORCE(void);
#define ASAppBarLayout_PENDING_ACTION_FORCE 8
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout, PENDING_ACTION_FORCE, jint)

FOUNDATION_EXPORT void ASAppBarLayout_init(ASAppBarLayout *self);

FOUNDATION_EXPORT ASAppBarLayout *new_ASAppBarLayout_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayout *create_ASAppBarLayout_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout)

@compatibility_alias ComGoogleAndroidMaterialAppbarAppBarLayout ASAppBarLayout;

#endif

#if !defined (ASAppBarLayout_BaseOnOffsetChangedListener_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout_BaseOnOffsetChangedListener))
#define ASAppBarLayout_BaseOnOffsetChangedListener_

@class ASAppBarLayout;

@protocol ASAppBarLayout_BaseOnOffsetChangedListener < JavaObject >

- (void)onOffsetChangedWithASAppBarLayout:(ASAppBarLayout *)appBarLayout
                                  withInt:(jint)verticalOffset;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout_BaseOnOffsetChangedListener)

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout_BaseOnOffsetChangedListener)

#endif

#if !defined (ASAppBarLayout_OnOffsetChangedListener_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout_OnOffsetChangedListener))
#define ASAppBarLayout_OnOffsetChangedListener_

@class ASAppBarLayout;

@protocol ASAppBarLayout_OnOffsetChangedListener < ASAppBarLayout_BaseOnOffsetChangedListener, JavaObject >

- (void)onOffsetChangedWithASAppBarLayout:(ASAppBarLayout *)appBarLayout
                                  withInt:(jint)verticalOffset;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout_OnOffsetChangedListener)

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout_OnOffsetChangedListener)

#endif

#if !defined (ASAppBarLayout_LiftOnScrollListener_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout_LiftOnScrollListener))
#define ASAppBarLayout_LiftOnScrollListener_

@protocol ASAppBarLayout_LiftOnScrollListener < JavaObject >

- (void)onUpdateWithFloat:(jfloat)elevation
                  withInt:(jint)backgroundColor;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout_LiftOnScrollListener)

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout_LiftOnScrollListener)

#endif

#if !defined (ASAppBarLayout_LayoutParams_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout_LayoutParams))
#define ASAppBarLayout_LayoutParams_

#define RESTRICT_LinearLayout 1
#define INCLUDE_ADLinearLayout_LayoutParams 1
#include "LinearLayout.h"

@class ADViewGroup_LayoutParams;
@class ASAppBarLayout_ChildScrollEffect;
@protocol ADInterpolator;

@interface ASAppBarLayout_LayoutParams : ADLinearLayout_LayoutParams {
 @public
  jint scrollFlags_;
  id<ADInterpolator> scrollInterpolator_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)width
                    withInt:(jint)height;

- (instancetype)initWithInt:(jint)width
                    withInt:(jint)height
                  withFloat:(jfloat)weight;

- (instancetype)initWithADViewGroup_LayoutParams:(ADViewGroup_LayoutParams *)p;

- (instancetype)initWithASAppBarLayout_LayoutParams:(ASAppBarLayout_LayoutParams *)source;

- (ASAppBarLayout_ChildScrollEffect *)getScrollEffect;

- (jint)getScrollFlags;

- (id<ADInterpolator>)getScrollInterpolator;

- (void)setScrollFlagsWithInt:(jint)flags;

- (void)setScrollInterpolatorWithADInterpolator:(id<ADInterpolator>)interpolator;

#pragma mark Package-Private

- (jboolean)isCollapsible;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithADLinearLayout_LayoutParams:(ADLinearLayout_LayoutParams *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout_LayoutParams)

J2OBJC_FIELD_SETTER(ASAppBarLayout_LayoutParams, scrollInterpolator_, id<ADInterpolator>)

inline jint ASAppBarLayout_LayoutParams_get_SCROLL_FLAG_NO_SCROLL(void);
#define ASAppBarLayout_LayoutParams_SCROLL_FLAG_NO_SCROLL 0
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, SCROLL_FLAG_NO_SCROLL, jint)

inline jint ASAppBarLayout_LayoutParams_get_SCROLL_FLAG_SCROLL(void);
#define ASAppBarLayout_LayoutParams_SCROLL_FLAG_SCROLL 1
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, SCROLL_FLAG_SCROLL, jint)

inline jint ASAppBarLayout_LayoutParams_get_SCROLL_FLAG_EXIT_UNTIL_COLLAPSED(void);
#define ASAppBarLayout_LayoutParams_SCROLL_FLAG_EXIT_UNTIL_COLLAPSED 2
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, SCROLL_FLAG_EXIT_UNTIL_COLLAPSED, jint)

inline jint ASAppBarLayout_LayoutParams_get_SCROLL_FLAG_ENTER_ALWAYS(void);
#define ASAppBarLayout_LayoutParams_SCROLL_FLAG_ENTER_ALWAYS 4
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, SCROLL_FLAG_ENTER_ALWAYS, jint)

inline jint ASAppBarLayout_LayoutParams_get_SCROLL_FLAG_ENTER_ALWAYS_COLLAPSED(void);
#define ASAppBarLayout_LayoutParams_SCROLL_FLAG_ENTER_ALWAYS_COLLAPSED 8
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, SCROLL_FLAG_ENTER_ALWAYS_COLLAPSED, jint)

inline jint ASAppBarLayout_LayoutParams_get_SCROLL_FLAG_SNAP(void);
#define ASAppBarLayout_LayoutParams_SCROLL_FLAG_SNAP 16
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, SCROLL_FLAG_SNAP, jint)

inline jint ASAppBarLayout_LayoutParams_get_SCROLL_FLAG_SNAP_MARGINS(void);
#define ASAppBarLayout_LayoutParams_SCROLL_FLAG_SNAP_MARGINS 32
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, SCROLL_FLAG_SNAP_MARGINS, jint)

inline jint ASAppBarLayout_LayoutParams_get_FLAG_QUICK_RETURN(void);
#define ASAppBarLayout_LayoutParams_FLAG_QUICK_RETURN 5
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, FLAG_QUICK_RETURN, jint)

inline jint ASAppBarLayout_LayoutParams_get_FLAG_SNAP(void);
#define ASAppBarLayout_LayoutParams_FLAG_SNAP 17
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, FLAG_SNAP, jint)

inline jint ASAppBarLayout_LayoutParams_get_COLLAPSIBLE_FLAGS(void);
#define ASAppBarLayout_LayoutParams_COLLAPSIBLE_FLAGS 10
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, COLLAPSIBLE_FLAGS, jint)

inline jint ASAppBarLayout_LayoutParams_get_SCROLL_EFFECT_NONE(void);
#define ASAppBarLayout_LayoutParams_SCROLL_EFFECT_NONE 0
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, SCROLL_EFFECT_NONE, jint)

inline jint ASAppBarLayout_LayoutParams_get_SCROLL_EFFECT_COMPRESS(void);
#define ASAppBarLayout_LayoutParams_SCROLL_EFFECT_COMPRESS 1
J2OBJC_STATIC_FIELD_CONSTANT(ASAppBarLayout_LayoutParams, SCROLL_EFFECT_COMPRESS, jint)

FOUNDATION_EXPORT void ASAppBarLayout_LayoutParams_initWithInt_withInt_(ASAppBarLayout_LayoutParams *self, jint width, jint height);

FOUNDATION_EXPORT ASAppBarLayout_LayoutParams *new_ASAppBarLayout_LayoutParams_initWithInt_withInt_(jint width, jint height) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayout_LayoutParams *create_ASAppBarLayout_LayoutParams_initWithInt_withInt_(jint width, jint height);

FOUNDATION_EXPORT void ASAppBarLayout_LayoutParams_initWithInt_withInt_withFloat_(ASAppBarLayout_LayoutParams *self, jint width, jint height, jfloat weight);

FOUNDATION_EXPORT ASAppBarLayout_LayoutParams *new_ASAppBarLayout_LayoutParams_initWithInt_withInt_withFloat_(jint width, jint height, jfloat weight) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayout_LayoutParams *create_ASAppBarLayout_LayoutParams_initWithInt_withInt_withFloat_(jint width, jint height, jfloat weight);

FOUNDATION_EXPORT void ASAppBarLayout_LayoutParams_initWithADViewGroup_LayoutParams_(ASAppBarLayout_LayoutParams *self, ADViewGroup_LayoutParams *p);

FOUNDATION_EXPORT ASAppBarLayout_LayoutParams *new_ASAppBarLayout_LayoutParams_initWithADViewGroup_LayoutParams_(ADViewGroup_LayoutParams *p) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayout_LayoutParams *create_ASAppBarLayout_LayoutParams_initWithADViewGroup_LayoutParams_(ADViewGroup_LayoutParams *p);

FOUNDATION_EXPORT void ASAppBarLayout_LayoutParams_initWithASAppBarLayout_LayoutParams_(ASAppBarLayout_LayoutParams *self, ASAppBarLayout_LayoutParams *source);

FOUNDATION_EXPORT ASAppBarLayout_LayoutParams *new_ASAppBarLayout_LayoutParams_initWithASAppBarLayout_LayoutParams_(ASAppBarLayout_LayoutParams *source) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayout_LayoutParams *create_ASAppBarLayout_LayoutParams_initWithASAppBarLayout_LayoutParams_(ASAppBarLayout_LayoutParams *source);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout_LayoutParams)

#endif

#if !defined (ASAppBarLayout_BaseBehavior_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout_BaseBehavior))
#define ASAppBarLayout_BaseBehavior_

#define RESTRICT_HeaderBehavior 1
#define INCLUDE_ASHeaderBehavior 1
#include "HeaderBehavior.h"

@class ADView;
@class ADXCoordinatorLayout;
@class ASAppBarLayout;
@class ASAppBarLayout_BaseBehavior_BaseDragCallback;
@class ASAppBarLayout_SavedState;
@class IOSIntArray;

@interface ASAppBarLayout_BaseBehavior : ASHeaderBehavior

#pragma mark Public

- (instancetype)init;

- (jboolean)onLayoutChildWithADXCoordinatorLayout:(ADXCoordinatorLayout *)parent
                                       withADView:(ASAppBarLayout *)abl
                                          withInt:(jint)layoutDirection;

- (jboolean)onMeasureChildWithADXCoordinatorLayout:(ADXCoordinatorLayout *)parent
                                        withADView:(ASAppBarLayout *)child
                                           withInt:(jint)parentWidthMeasureSpec
                                           withInt:(jint)widthUsed
                                           withInt:(jint)parentHeightMeasureSpec
                                           withInt:(jint)heightUsed;

- (void)onNestedPreScrollWithADXCoordinatorLayout:(ADXCoordinatorLayout *)coordinatorLayout
                                       withADView:(ASAppBarLayout *)child
                                       withADView:(ADView *)target
                                          withInt:(jint)dx
                                          withInt:(jint)dy
                                     withIntArray:(IOSIntArray *)consumed
                                          withInt:(jint)type;

- (void)onNestedScrollWithADXCoordinatorLayout:(ADXCoordinatorLayout *)coordinatorLayout
                                    withADView:(ASAppBarLayout *)child
                                    withADView:(ADView *)target
                                       withInt:(jint)dxConsumed
                                       withInt:(jint)dyConsumed
                                       withInt:(jint)dxUnconsumed
                                       withInt:(jint)dyUnconsumed
                                       withInt:(jint)type
                                  withIntArray:(IOSIntArray *)consumed;

- (jboolean)onStartNestedScrollWithADXCoordinatorLayout:(ADXCoordinatorLayout *)parent
                                             withADView:(ASAppBarLayout *)child
                                             withADView:(ADView *)directTargetChild
                                             withADView:(ADView *)target
                                                withInt:(jint)nestedScrollAxes
                                                withInt:(jint)type;

- (void)onStopNestedScrollWithADXCoordinatorLayout:(ADXCoordinatorLayout *)coordinatorLayout
                                        withADView:(ASAppBarLayout *)abl
                                        withADView:(ADView *)target
                                           withInt:(jint)type;

- (void)setDragCallbackWithASAppBarLayout_BaseBehavior_BaseDragCallback:(ASAppBarLayout_BaseBehavior_BaseDragCallback *)callback;

#pragma mark Package-Private

- (jboolean)canDragViewWithADView:(ASAppBarLayout *)view;

- (jint)getMaxDragOffsetWithADView:(ASAppBarLayout *)view;

- (jint)getScrollRangeForDragFlingWithADView:(ASAppBarLayout *)view;

- (jint)getTopBottomOffsetForScrollingSibling;

- (jboolean)isOffsetAnimatorRunning;

- (void)onFlingFinishedWithADXCoordinatorLayout:(ADXCoordinatorLayout *)parent
                                     withADView:(ASAppBarLayout *)layout;

- (void)restoreScrollStateWithASAppBarLayout_SavedState:(ASAppBarLayout_SavedState *)state
                                            withBoolean:(jboolean)force;

- (jint)setHeaderTopBottomOffsetWithADXCoordinatorLayout:(ADXCoordinatorLayout *)coordinatorLayout
                                              withADView:(ASAppBarLayout *)appBarLayout
                                                 withInt:(jint)newOffset
                                                 withInt:(jint)minOffset
                                                 withInt:(jint)maxOffset;

// Disallowed inherited constructors, do not use.

- (instancetype)initPackagePrivate NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout_BaseBehavior)

FOUNDATION_EXPORT void ASAppBarLayout_BaseBehavior_init(ASAppBarLayout_BaseBehavior *self);

FOUNDATION_EXPORT ASAppBarLayout_BaseBehavior *new_ASAppBarLayout_BaseBehavior_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayout_BaseBehavior *create_ASAppBarLayout_BaseBehavior_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout_BaseBehavior)

#endif

#if !defined (ASAppBarLayout_Behavior_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout_Behavior))
#define ASAppBarLayout_Behavior_

@interface ASAppBarLayout_Behavior : ASAppBarLayout_BaseBehavior

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout_Behavior)

FOUNDATION_EXPORT void ASAppBarLayout_Behavior_init(ASAppBarLayout_Behavior *self);

FOUNDATION_EXPORT ASAppBarLayout_Behavior *new_ASAppBarLayout_Behavior_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayout_Behavior *create_ASAppBarLayout_Behavior_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout_Behavior)

#endif

#if !defined (ASAppBarLayout_BaseBehavior_BaseDragCallback_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout_BaseBehavior_BaseDragCallback))
#define ASAppBarLayout_BaseBehavior_BaseDragCallback_

@class ASAppBarLayout;

@interface ASAppBarLayout_BaseBehavior_BaseDragCallback : NSObject

#pragma mark Public

- (instancetype)init;

- (jboolean)canDragWithASAppBarLayout:(ASAppBarLayout *)appBarLayout;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout_BaseBehavior_BaseDragCallback)

FOUNDATION_EXPORT void ASAppBarLayout_BaseBehavior_BaseDragCallback_init(ASAppBarLayout_BaseBehavior_BaseDragCallback *self);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout_BaseBehavior_BaseDragCallback)

#endif

#if !defined (ASAppBarLayout_ScrollingViewBehavior_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout_ScrollingViewBehavior))
#define ASAppBarLayout_ScrollingViewBehavior_

#define RESTRICT_HeaderScrollingViewBehavior 1
#define INCLUDE_ASHeaderScrollingViewBehavior 1
#include "HeaderScrollingViewBehavior.h"

@class ADAttributeSet;
@class ADContext;
@class ADRect;
@class ADView;
@class ADXCoordinatorLayout;
@class ASAppBarLayout;
@protocol JavaUtilList;

@interface ASAppBarLayout_ScrollingViewBehavior : ASHeaderScrollingViewBehavior

#pragma mark Public

- (instancetype)init;

- (jboolean)layoutDependsOnWithADXCoordinatorLayout:(ADXCoordinatorLayout *)parent
                                         withADView:(ADView *)child
                                         withADView:(ADView *)dependency;

- (jboolean)onDependentViewChangedWithADXCoordinatorLayout:(ADXCoordinatorLayout *)parent
                                                withADView:(ADView *)child
                                                withADView:(ADView *)dependency;

- (void)onDependentViewRemovedWithADXCoordinatorLayout:(ADXCoordinatorLayout *)parent
                                            withADView:(ADView *)child
                                            withADView:(ADView *)dependency;

- (jboolean)onRequestChildRectangleOnScreenWithADXCoordinatorLayout:(ADXCoordinatorLayout *)parent
                                                         withADView:(ADView *)child
                                                         withADRect:(ADRect *)rectangle
                                                        withBoolean:(jboolean)immediate;

#pragma mark Package-Private

- (ASAppBarLayout *)findFirstDependencyWithJavaUtilList:(id<JavaUtilList>)views;

- (jfloat)getOverlapRatioForOffsetWithADView:(ADView *)header;

- (jint)getScrollRangeWithADView:(ADView *)v;

// Disallowed inherited constructors, do not use.

- (instancetype)initPackagePrivate NS_UNAVAILABLE;

- (instancetype)initPackagePrivateWithADContext:(ADContext *)arg0
                             withADAttributeSet:(ADAttributeSet *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout_ScrollingViewBehavior)

FOUNDATION_EXPORT void ASAppBarLayout_ScrollingViewBehavior_init(ASAppBarLayout_ScrollingViewBehavior *self);

FOUNDATION_EXPORT ASAppBarLayout_ScrollingViewBehavior *new_ASAppBarLayout_ScrollingViewBehavior_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayout_ScrollingViewBehavior *create_ASAppBarLayout_ScrollingViewBehavior_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout_ScrollingViewBehavior)

#endif

#if !defined (ASAppBarLayout_ChildScrollEffect_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout_ChildScrollEffect))
#define ASAppBarLayout_ChildScrollEffect_

@class ADView;
@class ASAppBarLayout;

@interface ASAppBarLayout_ChildScrollEffect : NSObject

#pragma mark Public

- (instancetype)init;

- (void)onOffsetChangedWithASAppBarLayout:(ASAppBarLayout *)appBarLayout
                               withADView:(ADView *)child
                                withFloat:(jfloat)offset;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout_ChildScrollEffect)

FOUNDATION_EXPORT void ASAppBarLayout_ChildScrollEffect_init(ASAppBarLayout_ChildScrollEffect *self);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout_ChildScrollEffect)

#endif

#if !defined (ASAppBarLayout_SavedState_) && (INCLUDE_ALL_AppBarLayout || defined(INCLUDE_ASAppBarLayout_SavedState))
#define ASAppBarLayout_SavedState_

@class ASAppBarLayout;

@interface ASAppBarLayout_SavedState : NSObject {
 @public
  jboolean fullyScrolled_;
  jboolean fullyExpanded_;
  jint firstVisibleChildIndex_;
  jfloat firstVisibleChildPercentageShown_;
  jboolean firstVisibleChildAtMinimumHeight_;
}

#pragma mark Package-Private

- (instancetype)initWithASAppBarLayout:(ASAppBarLayout *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayout_SavedState)

FOUNDATION_EXPORT void ASAppBarLayout_SavedState_initWithASAppBarLayout_(ASAppBarLayout_SavedState *self, ASAppBarLayout *outer$);

FOUNDATION_EXPORT ASAppBarLayout_SavedState *new_ASAppBarLayout_SavedState_initWithASAppBarLayout_(ASAppBarLayout *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayout_SavedState *create_ASAppBarLayout_SavedState_initWithASAppBarLayout_(ASAppBarLayout *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayout_SavedState)

#endif

#pragma pop_macro("INCLUDE_ALL_AppBarLayout")
