//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAppBarLayoutPlugin\src\main\java\com\ashera\appbarlayout\AppBarLayoutPlugin.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AppBarLayoutPlugin")
#ifdef RESTRICT_AppBarLayoutPlugin
#define INCLUDE_ALL_AppBarLayoutPlugin 0
#else
#define INCLUDE_ALL_AppBarLayoutPlugin 1
#endif
#undef RESTRICT_AppBarLayoutPlugin

#if !defined (ASAppBarLayoutPlugin_) && (INCLUDE_ALL_AppBarLayoutPlugin || defined(INCLUDE_ASAppBarLayoutPlugin))
#define ASAppBarLayoutPlugin_

@interface ASAppBarLayoutPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutPlugin)

FOUNDATION_EXPORT void ASAppBarLayoutPlugin_init(ASAppBarLayoutPlugin *self);

FOUNDATION_EXPORT ASAppBarLayoutPlugin *new_ASAppBarLayoutPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutPlugin *create_ASAppBarLayoutPlugin_init(void);

FOUNDATION_EXPORT void ASAppBarLayoutPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutPlugin)

@compatibility_alias ComAsheraAppbarlayoutAppBarLayoutPlugin ASAppBarLayoutPlugin;

#endif

#pragma pop_macro("INCLUDE_ALL_AppBarLayoutPlugin")
