//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAppBarLayoutPlugin\src\main\java\com\ashera\appbarlayout\AppBarLayoutImpl.java
//

#include "AbstractBitFlagConverter.h"
#include "AppBarLayout.h"
#include "AppBarLayoutImpl.h"
#include "BaseHasWidgets.h"
#include "ConverterFactory.h"
#include "HasWidgets.h"
#include "IAttributable.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "Interpolator.h"
#include "J2ObjC_source.h"
#include "LayoutTransition.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "Rect.h"
#include "View.h"
#include "ViewGroup.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/lang/Runnable.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"
#include "HasLifeCycleDecorators.h"

@protocol JavaUtilMap;


#pragma clang diagnostic ignored "-Wprotocol"
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface ASAppBarLayoutImpl () {
 @public
  id uiView_;
  ASAppBarLayout *appBarLayout_;
  ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *builder_;
  ASAppBarLayoutImpl_AppBarLayoutBean *bean_;
  ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *paramsBuilder_;
  ASAppBarLayoutImpl_AppBarLayoutParamsBean *paramsBean_;
}

- (void)setWidgetOnNativeClass;

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget;

- (void)createLayoutParamsWithADView:(ADView *)view;

- (ASAppBarLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view;

- (void)setScrollInterpolatorWithASAppBarLayout_LayoutParams:(ASAppBarLayout_LayoutParams *)layoutParams
                                                      withId:(id)objValue;

@end

J2OBJC_FIELD_SETTER(ASAppBarLayoutImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASAppBarLayoutImpl, appBarLayout_, ASAppBarLayout *)
J2OBJC_FIELD_SETTER(ASAppBarLayoutImpl, builder_, ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)
J2OBJC_FIELD_SETTER(ASAppBarLayoutImpl, bean_, ASAppBarLayoutImpl_AppBarLayoutBean *)
J2OBJC_FIELD_SETTER(ASAppBarLayoutImpl, paramsBuilder_, ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)
J2OBJC_FIELD_SETTER(ASAppBarLayoutImpl, paramsBean_, ASAppBarLayoutImpl_AppBarLayoutParamsBean *)

__attribute__((unused)) static void ASAppBarLayoutImpl_setWidgetOnNativeClass(ASAppBarLayoutImpl *self);

__attribute__((unused)) static void ASAppBarLayoutImpl_nativeRemoveViewWithASIWidget_(ASAppBarLayoutImpl *self, id<ASIWidget> widget);

__attribute__((unused)) static void ASAppBarLayoutImpl_createLayoutParamsWithADView_(ASAppBarLayoutImpl *self, ADView *view);

__attribute__((unused)) static ASAppBarLayout_LayoutParams *ASAppBarLayoutImpl_getLayoutParamsWithADView_(ASAppBarLayoutImpl *self, ADView *view);

__attribute__((unused)) static void ASAppBarLayoutImpl_setScrollInterpolatorWithASAppBarLayout_LayoutParams_withId_(ASAppBarLayoutImpl *self, ASAppBarLayout_LayoutParams *layoutParams, id objValue);

@interface ASAppBarLayoutImpl_Layout_scrollFlags () {
 @public
  id<JavaUtilMap> mapping_;
}

@end

J2OBJC_FIELD_SETTER(ASAppBarLayoutImpl_Layout_scrollFlags, mapping_, id<JavaUtilMap>)

@interface ASAppBarLayoutImpl_AppBarLayoutExt () {
 @public
  __unsafe_unretained ASAppBarLayoutImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  jint mMaxWidth_;
  jint mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASAppBarLayoutImpl_AppBarLayoutExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASAppBarLayoutImpl_AppBarLayoutExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASAppBarLayoutImpl_AppBarLayoutExt, templates_, id<JavaUtilMap>)

@interface ASAppBarLayoutImpl_AppBarLayoutCommandBuilder () {
 @public
  ASAppBarLayoutImpl *this$0_;
}

@end

@interface ASAppBarLayoutImpl_AppBarLayoutBean () {
 @public
  ASAppBarLayoutImpl *this$0_;
}

@end

@interface ASAppBarLayoutImpl_AppBarLayoutParamsBean () {
 @public
  ASAppBarLayoutImpl *this$0_;
}

@end

@interface ASAppBarLayoutImpl_$Lambda$1 : NSObject < JavaLangRunnable > {
 @public
  id<ASIWidget> val$widget_;
}

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl_$Lambda$1)

__attribute__((unused)) static void ASAppBarLayoutImpl_$Lambda$1_initWithASIWidget_(ASAppBarLayoutImpl_$Lambda$1 *self, id<ASIWidget> capture$0);

__attribute__((unused)) static ASAppBarLayoutImpl_$Lambda$1 *new_ASAppBarLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASAppBarLayoutImpl_$Lambda$1 *create_ASAppBarLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0);

NSString *ASAppBarLayoutImpl_LOCAL_NAME = @"com.google.android.material.appbar.AppBarLayout";
NSString *ASAppBarLayoutImpl_GROUP_NAME = @"com.google.android.material.appbar.AppBarLayout";

@implementation ASAppBarLayoutImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASViewGroupImpl_register__WithNSString_(localName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"expanded"])) withTypeWithNSString:@"boolean"]);
  ASConverterFactory_register__WithNSString_withASIConverter_(@"com.google.android.material.appbar.AppBarLayout.layout_scrollFlags", new_ASAppBarLayoutImpl_Layout_scrollFlags_init());
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_scrollFlags"])) withTypeWithNSString:@"com.google.android.material.appbar.AppBarLayout.layout_scrollFlags"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_scrollInterpolator"])) withTypeWithNSString:@"string"])) forChild]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASAppBarLayoutImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASAppBarLayoutImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASAppBarLayoutImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (id<ASIWidget>)newInstance {
  return new_ASAppBarLayoutImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  appBarLayout_ = new_ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(self);
  [self nativeCreateWithJavaUtilMap:params];
  ASViewGroupImpl_registerCommandConveterWithASIWidget_(self);
  ASAppBarLayoutImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASAppBarLayoutImpl_setWidgetOnNativeClass(self);
}

- (id)asWidget {
  return appBarLayout_;
}

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w {
  jboolean remove = [super removeWithASIWidget:w];
  [((ASAppBarLayout *) nil_chk(appBarLayout_)) removeViewWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class])];
  ASAppBarLayoutImpl_nativeRemoveViewWithASIWidget_(self, w);
  return remove;
}

- (jboolean)removeWithInt:(jint)index {
  id<ASIWidget> widget = [((id<JavaUtilList>) nil_chk(widgets_)) getWithInt:index];
  jboolean remove = [super removeWithInt:index];
  if (index + 1 <= [((ASAppBarLayout *) nil_chk(appBarLayout_)) getChildCount]) {
    [((ASAppBarLayout *) nil_chk(appBarLayout_)) removeViewAtWithInt:index];
    ASAppBarLayoutImpl_nativeRemoveViewWithASIWidget_(self, widget);
  }
  return remove;
}

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget {
  ASAppBarLayoutImpl_nativeRemoveViewWithASIWidget_(self, widget);
}

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index {
  if (index != -2) {
    ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
    ASAppBarLayoutImpl_createLayoutParamsWithADView_(self, view);
    if (index == -1) {
      [((ASAppBarLayout *) nil_chk(appBarLayout_)) addViewWithADView:view];
    }
    else {
      [((ASAppBarLayout *) nil_chk(appBarLayout_)) addViewWithADView:view withInt:index];
    }
  }
  ASViewGroupImpl_nativeAddViewWithId_withId_([self asNativeWidget], [((id<ASIWidget>) nil_chk(w)) asNativeWidget]);
  [super addWithASIWidget:w withInt:index];
}

- (void)createLayoutParamsWithADView:(ADView *)view {
  ASAppBarLayoutImpl_createLayoutParamsWithADView_(self, view);
}

- (ASAppBarLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view {
  return ASAppBarLayoutImpl_getLayoutParamsWithADView_(self, view);
}

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ASAppBarLayout_LayoutParams *layoutParams = ASAppBarLayoutImpl_getLayoutParamsWithADView_(self, view);
  ASViewGroupImpl_setChildAttributeWithASIWidget_withASWidgetAttribute_withId_withId_(w, key, objValue, layoutParams);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_scrollFlags", @"layout_scrollInterpolator" }, 4)) {
    case 0:
    ((ASAppBarLayout_LayoutParams *) nil_chk(layoutParams))->width_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 1:
    ((ASAppBarLayout_LayoutParams *) nil_chk(layoutParams))->height_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 2:
    {
      [((ASAppBarLayout_LayoutParams *) nil_chk(layoutParams)) setScrollFlagsWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 3:
    {
      ASAppBarLayoutImpl_setScrollInterpolatorWithASAppBarLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    default:
    break;
  }
  [((ADView *) nil_chk(view)) setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
}

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key {
  id attributeValue = ASViewGroupImpl_getChildAttributeWithASIWidget_withASWidgetAttribute_(w, key);
  if (attributeValue != nil) {
    return attributeValue;
  }
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ASAppBarLayout_LayoutParams *layoutParams = ASAppBarLayoutImpl_getLayoutParamsWithADView_(self, view);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height" }, 2)) {
    case 0:
    return JavaLangInteger_valueOfWithInt_(((ASAppBarLayout_LayoutParams *) nil_chk(layoutParams))->width_);
    case 1:
    return JavaLangInteger_valueOfWithInt_(((ASAppBarLayout_LayoutParams *) nil_chk(layoutParams))->height_);
  }
  return nil;
}

- (IOSClass *)getViewClass {
  return ASAppBarLayoutImpl_AppBarLayoutExt_class_();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ASViewGroupImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"expanded" }, 1)) {
    case 0:
    {
      [((ASAppBarLayout *) nil_chk(appBarLayout_)) setExpandedWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
    }
    break;
    default:
    break;
  }
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id attributeValue = ASViewGroupImpl_getAttributeWithASIWidget_withASWidgetAttribute_withASILifeCycleDecorator_(self, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){  }, 0)) {
  }
  return nil;
}

- (id)asNativeWidget {
  return uiView_;
}

- (jboolean)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  uiView_ = uiView;
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)setScrollInterpolatorWithASAppBarLayout_LayoutParams:(ASAppBarLayout_LayoutParams *)layoutParams
                                                      withId:(id)objValue {
  ASAppBarLayoutImpl_setScrollInterpolatorWithASAppBarLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ASAppBarLayout *) nil_chk(appBarLayout_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(jboolean)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

- (id)getPluginWithNSString:(NSString *)plugin {
  return [((id<ASIAttributable>) nil_chk(ASWidgetFactory_getAttributableWithNSString_(plugin))) newInstanceWithASIWidget:self];
}

- (ASAppBarLayoutImpl_AppBarLayoutBean *)getBean {
  if (bean_ == nil) {
    bean_ = new_ASAppBarLayoutImpl_AppBarLayoutBean_initWithASAppBarLayoutImpl_(self);
  }
  return bean_;
}

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)getBuilder {
  if (builder_ == nil) {
    builder_ = new_ASAppBarLayoutImpl_AppBarLayoutCommandBuilder_initWithASAppBarLayoutImpl_(self);
  }
  return builder_;
}

- (ASAppBarLayoutImpl_AppBarLayoutParamsBean *)getParamsBean {
  if (paramsBean_ == nil) {
    paramsBean_ = new_ASAppBarLayoutImpl_AppBarLayoutParamsBean_initWithASAppBarLayoutImpl_(self);
  }
  return paramsBean_;
}

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)getParamsBuilder {
  if (paramsBuilder_ == nil) {
    paramsBuilder_ = new_ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder_initWithASAppBarLayoutImpl_(self);
  }
  return paramsBuilder_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 9, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 12, 13, -1, -1, -1, -1 },
    { NULL, "LASAppBarLayout_LayoutParams;", 0x2, 14, 13, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 15, 16, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 17, 18, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 19, 20, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 21, 22, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 23, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 24, 25, -1, 26, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 27, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 30, 31, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 32, 1, -1, -1, -1, -1 },
    { NULL, "LASAppBarLayoutImpl_AppBarLayoutBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASAppBarLayoutImpl_AppBarLayoutCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASAppBarLayoutImpl_AppBarLayoutParamsBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(newInstance);
  methods[5].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[6].selector = @selector(setWidgetOnNativeClass);
  methods[7].selector = @selector(asWidget);
  methods[8].selector = @selector(removeWithASIWidget:);
  methods[9].selector = @selector(removeWithInt:);
  methods[10].selector = @selector(nativeRemoveViewWithASIWidget:);
  methods[11].selector = @selector(addWithASIWidget:withInt:);
  methods[12].selector = @selector(createLayoutParamsWithADView:);
  methods[13].selector = @selector(getLayoutParamsWithADView:);
  methods[14].selector = @selector(setChildAttributeWithASIWidget:withASWidgetAttribute:withNSString:withId:);
  methods[15].selector = @selector(getChildAttributeWithASIWidget:withASWidgetAttribute:);
  methods[16].selector = @selector(getViewClass);
  methods[17].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[18].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[19].selector = @selector(asNativeWidget);
  methods[20].selector = @selector(checkIosVersionWithNSString:);
  methods[21].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[22].selector = @selector(requestLayout);
  methods[23].selector = @selector(invalidate);
  methods[24].selector = @selector(setScrollInterpolatorWithASAppBarLayout_LayoutParams:withId:);
  methods[25].selector = @selector(setIdWithNSString:);
  methods[26].selector = @selector(setVisibleWithBoolean:);
  methods[27].selector = @selector(getPluginWithNSString:);
  methods[28].selector = @selector(getBean);
  methods[29].selector = @selector(getBuilder);
  methods[30].selector = @selector(getParamsBean);
  methods[31].selector = @selector(getParamsBuilder);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 33, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 34, -1, -1 },
    { "appBarLayout_", "LASAppBarLayout;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "builder_", "LASAppBarLayoutImpl_AppBarLayoutCommandBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "bean_", "LASAppBarLayoutImpl_AppBarLayoutBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBuilder_", "LASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBean_", "LASAppBarLayoutImpl_AppBarLayoutParamsBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "remove", "LASIWidget;", "I", "nativeRemoveView", "add", "LASIWidget;I", "createLayoutParams", "LADView;", "getLayoutParams", "setChildAttribute", "LASIWidget;LASWidgetAttribute;LNSString;LNSObject;", "getChildAttribute", "LASIWidget;LASWidgetAttribute;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "checkIosVersion", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setScrollInterpolator", "LASAppBarLayout_LayoutParams;LNSObject;", "setId", "setVisible", "Z", "getPlugin", &ASAppBarLayoutImpl_LOCAL_NAME, &ASAppBarLayoutImpl_GROUP_NAME, "LASAppBarLayoutImpl_Layout_scrollFlags;LASAppBarLayoutImpl_AppBarLayoutExt;LASAppBarLayoutImpl_AppBarLayoutCommandBuilder;LASAppBarLayoutImpl_AppBarLayoutBean;LASAppBarLayoutImpl_AppBarLayoutParamsBean;LASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder;" };
  static const J2ObjcClassInfo _ASAppBarLayoutImpl = { "AppBarLayoutImpl", "com.ashera.appbarlayout", ptrTable, methods, fields, 7, 0x1, 32, 8, -1, 35, -1, -1, -1 };
  return &_ASAppBarLayoutImpl;
}

@end

void ASAppBarLayoutImpl_init(ASAppBarLayoutImpl *self) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASAppBarLayoutImpl_GROUP_NAME, ASAppBarLayoutImpl_LOCAL_NAME);
}

ASAppBarLayoutImpl *new_ASAppBarLayoutImpl_init() {
  J2OBJC_NEW_IMPL(ASAppBarLayoutImpl, init)
}

ASAppBarLayoutImpl *create_ASAppBarLayoutImpl_init() {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutImpl, init)
}

void ASAppBarLayoutImpl_initWithNSString_(ASAppBarLayoutImpl *self, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASAppBarLayoutImpl_GROUP_NAME, localname);
}

ASAppBarLayoutImpl *new_ASAppBarLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASAppBarLayoutImpl, initWithNSString_, localname)
}

ASAppBarLayoutImpl *create_ASAppBarLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutImpl, initWithNSString_, localname)
}

void ASAppBarLayoutImpl_initWithNSString_withNSString_(ASAppBarLayoutImpl *self, NSString *groupName, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, groupName, localname);
}

ASAppBarLayoutImpl *new_ASAppBarLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASAppBarLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

ASAppBarLayoutImpl *create_ASAppBarLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASAppBarLayoutImpl_setWidgetOnNativeClass(ASAppBarLayoutImpl *self) {
  ((ASUIView*) [self asNativeWidget]).widget = self;
}

void ASAppBarLayoutImpl_nativeRemoveViewWithASIWidget_(ASAppBarLayoutImpl *self, id<ASIWidget> widget) {
  ADLayoutTransition *layoutTransition = [((ASAppBarLayout *) nil_chk(self->appBarLayout_)) getLayoutTransition];
  if (layoutTransition != nil && ([layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_CHANGE_DISAPPEARING] || [layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_DISAPPEARING])) {
    [self addToBufferedRunnablesWithJavaLangRunnable:new_ASAppBarLayoutImpl_$Lambda$1_initWithASIWidget_(widget)];
  }
  else {
    ASViewGroupImpl_nativeRemoveViewWithASIWidget_(widget);
  }
}

void ASAppBarLayoutImpl_createLayoutParamsWithADView_(ASAppBarLayoutImpl *self, ADView *view) {
  ASAppBarLayout_LayoutParams *layoutParams = (ASAppBarLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ASAppBarLayout_LayoutParams class]);
  layoutParams = (ASAppBarLayout_LayoutParams *) cast_chk([view getLayoutParams], [ASAppBarLayout_LayoutParams class]);
  if (layoutParams == nil) {
    layoutParams = new_ASAppBarLayout_LayoutParams_initWithInt_withInt_(-2, -2);
    [view setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
  }
  else {
    layoutParams->height_ = -2;
    layoutParams->width_ = -2;
  }
}

ASAppBarLayout_LayoutParams *ASAppBarLayoutImpl_getLayoutParamsWithADView_(ASAppBarLayoutImpl *self, ADView *view) {
  return (ASAppBarLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ASAppBarLayout_LayoutParams class]);
}

void ASAppBarLayoutImpl_setScrollInterpolatorWithASAppBarLayout_LayoutParams_withId_(ASAppBarLayoutImpl *self, ASAppBarLayout_LayoutParams *layoutParams, id objValue) {
  [((ASAppBarLayout_LayoutParams *) nil_chk(layoutParams)) setScrollInterpolatorWithADInterpolator:ASViewImpl_getInterpolatorWithASIWidget_withId_(self, objValue)];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAppBarLayoutImpl)

@implementation ASAppBarLayoutImpl_Layout_scrollFlags

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASAppBarLayoutImpl_Layout_scrollFlags_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<JavaUtilMap>)getMapping {
  return mapping_;
}

- (JavaLangInteger *)getDefault {
  return JavaLangInteger_valueOfWithInt_(0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, -1, -1, -1, 0, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getMapping);
  methods[2].selector = @selector(getDefault);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mapping_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 1, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "LASAppBarLayoutImpl;" };
  static const J2ObjcClassInfo _ASAppBarLayoutImpl_Layout_scrollFlags = { "Layout_scrollFlags", "com.ashera.appbarlayout", ptrTable, methods, fields, 7, 0x18, 3, 1, 2, -1, -1, -1, -1 };
  return &_ASAppBarLayoutImpl_Layout_scrollFlags;
}

@end

void ASAppBarLayoutImpl_Layout_scrollFlags_init(ASAppBarLayoutImpl_Layout_scrollFlags *self) {
  ASAbstractBitFlagConverter_init(self);
  self->mapping_ = new_JavaUtilHashMap_init();
  {
    (void) [self->mapping_ putWithId:@"noScroll" withId:JavaLangInteger_valueOfWithInt_((jint) 0x0)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"scroll" withId:JavaLangInteger_valueOfWithInt_((jint) 0x1)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"exitUntilCollapsed" withId:JavaLangInteger_valueOfWithInt_((jint) 0x2)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"enterAlways" withId:JavaLangInteger_valueOfWithInt_((jint) 0x4)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"enterAlwaysCollapsed" withId:JavaLangInteger_valueOfWithInt_((jint) 0x8)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"snap" withId:JavaLangInteger_valueOfWithInt_((jint) 0x10)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"snapMargins" withId:JavaLangInteger_valueOfWithInt_((jint) 0x20)];
  }
}

ASAppBarLayoutImpl_Layout_scrollFlags *new_ASAppBarLayoutImpl_Layout_scrollFlags_init() {
  J2OBJC_NEW_IMPL(ASAppBarLayoutImpl_Layout_scrollFlags, init)
}

ASAppBarLayoutImpl_Layout_scrollFlags *create_ASAppBarLayoutImpl_Layout_scrollFlags_init() {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutImpl_Layout_scrollFlags, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAppBarLayoutImpl_Layout_scrollFlags)

@implementation ASAppBarLayoutImpl_AppBarLayoutExt

- (id<ASIWidget>)getWidget {
  return this$0_;
}

- (void)setMaxWidthWithInt:(jint)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(jint)height {
  mMaxHeight_ = height;
}

- (jint)getMaxWidth {
  return mMaxWidth_;
}

- (jint)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$ {
  ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$0_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:[this$0_ getParent]];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  if ([this$0_ getFragment] != nil) {
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$0_ getParent])) removeWithASIWidget:this$0_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(jint)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(jint)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  if ([((NSString *) nil_chk(name)) isEqual:@"state0"]) {
    [self setState0WithId:value];
    return;
  }
  if ([name isEqual:@"state1"]) {
    [self setState1WithId:value];
    return;
  }
  if ([name isEqual:@"state2"]) {
    [self setState2WithId:value];
    return;
  }
  if ([name isEqual:@"state3"]) {
    [self setState3WithId:value];
    return;
  }
  if ([name isEqual:@"state4"]) {
    [self setState4WithId:value];
    return;
  }
  [this$0_ setAttributeWithNSString:name withId:value withBoolean:true];
}

- (void)setVisibilityWithInt:(jint)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)setState0WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 0, value);
}

- (void)setState1WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 1, value);
}

- (void)setState2WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 2, value);
}

- (void)setState3WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 3, value);
}

- (void)setState4WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 4, value);
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$0_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$0_);
}

- (void)endViewTransitionWithADView:(ADView *)view {
  [super endViewTransitionWithADView:view];
  [this$0_ runBufferedRunnables];
}

- (void)__javaClone:(ASAppBarLayoutImpl_AppBarLayoutExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 32, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 34, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 35, 36, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASAppBarLayoutImpl:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(setState0WithId:);
  methods[26].selector = @selector(setState1WithId:);
  methods[27].selector = @selector(setState2WithId:);
  methods[28].selector = @selector(setState3WithId:);
  methods[29].selector = @selector(setState4WithId:);
  methods[30].selector = @selector(state0);
  methods[31].selector = @selector(state1);
  methods[32].selector = @selector(state2);
  methods[33].selector = @selector(state3);
  methods[34].selector = @selector(state4);
  methods[35].selector = @selector(stateYes);
  methods[36].selector = @selector(stateNo);
  methods[37].selector = @selector(endViewTransitionWithADView:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASAppBarLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 37, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASAppBarLayoutImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "setState0", "LNSObject;", "setState1", "setState2", "setState3", "setState4", "endViewTransition", "LADView;", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;" };
  static const J2ObjcClassInfo _ASAppBarLayoutImpl_AppBarLayoutExt = { "AppBarLayoutExt", "com.ashera.appbarlayout", ptrTable, methods, fields, 7, 0x1, 38, 6, 3, -1, -1, -1, -1 };
  return &_ASAppBarLayoutImpl_AppBarLayoutExt;
}

@end

void ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutExt *self, ASAppBarLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASAppBarLayout_init(self);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASAppBarLayoutImpl_AppBarLayoutExt *new_ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASAppBarLayoutImpl_AppBarLayoutExt, initWithASAppBarLayoutImpl_, outer$)
}

ASAppBarLayoutImpl_AppBarLayoutExt *create_ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutImpl_AppBarLayoutExt, initWithASAppBarLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAppBarLayoutImpl_AppBarLayoutExt)

@implementation ASAppBarLayoutImpl_AppBarLayoutCommandBuilder

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$ {
  ASAppBarLayoutImpl_AppBarLayoutCommandBuilder_initWithASAppBarLayoutImpl_(self, outer$);
  return self;
}

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter {
  if (setter) {
    [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
  [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return self;
}

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setExpandedWithBoolean:(jboolean)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"expanded"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:JavaLangBoolean_valueOfWithBoolean_(value)];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASAppBarLayoutImpl_AppBarLayoutCommandBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LASAppBarLayoutImpl_AppBarLayoutCommandBuilder;", 0x1, 3, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASAppBarLayoutImpl:);
  methods[1].selector = @selector(executeWithBoolean:);
  methods[2].selector = @selector(setExpandedWithBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASAppBarLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASAppBarLayoutImpl;", "execute", "Z", "setExpanded", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandBuilder<Lcom/ashera/appbarlayout/AppBarLayoutImpl$AppBarLayoutCommandBuilder;>;" };
  static const J2ObjcClassInfo _ASAppBarLayoutImpl_AppBarLayoutCommandBuilder = { "AppBarLayoutCommandBuilder", "com.ashera.appbarlayout", ptrTable, methods, fields, 7, 0x1, 3, 1, 0, -1, -1, 4, -1 };
  return &_ASAppBarLayoutImpl_AppBarLayoutCommandBuilder;
}

@end

void ASAppBarLayoutImpl_AppBarLayoutCommandBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *self, ASAppBarLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupCommandBuilder_init(self);
}

ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *new_ASAppBarLayoutImpl_AppBarLayoutCommandBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASAppBarLayoutImpl_AppBarLayoutCommandBuilder, initWithASAppBarLayoutImpl_, outer$)
}

ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *create_ASAppBarLayoutImpl_AppBarLayoutCommandBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutImpl_AppBarLayoutCommandBuilder, initWithASAppBarLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAppBarLayoutImpl_AppBarLayoutCommandBuilder)

@implementation ASAppBarLayoutImpl_AppBarLayoutBean

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$ {
  ASAppBarLayoutImpl_AppBarLayoutBean_initWithASAppBarLayoutImpl_(self, outer$);
  return self;
}

- (void)setExpandedWithBoolean:(jboolean)value {
  (void) [((ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *) nil_chk([((ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *) nil_chk([((ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setExpandedWithBoolean:value])) executeWithBoolean:true];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASAppBarLayoutImpl:);
  methods[1].selector = @selector(setExpandedWithBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASAppBarLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASAppBarLayoutImpl;", "setExpanded", "Z" };
  static const J2ObjcClassInfo _ASAppBarLayoutImpl_AppBarLayoutBean = { "AppBarLayoutBean", "com.ashera.appbarlayout", ptrTable, methods, fields, 7, 0x1, 2, 1, 0, -1, -1, -1, -1 };
  return &_ASAppBarLayoutImpl_AppBarLayoutBean;
}

@end

void ASAppBarLayoutImpl_AppBarLayoutBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutBean *self, ASAppBarLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupBean_initWithASIWidget_(self, outer$);
}

ASAppBarLayoutImpl_AppBarLayoutBean *new_ASAppBarLayoutImpl_AppBarLayoutBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASAppBarLayoutImpl_AppBarLayoutBean, initWithASAppBarLayoutImpl_, outer$)
}

ASAppBarLayoutImpl_AppBarLayoutBean *create_ASAppBarLayoutImpl_AppBarLayoutBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutImpl_AppBarLayoutBean, initWithASAppBarLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAppBarLayoutImpl_AppBarLayoutBean)

@implementation ASAppBarLayoutImpl_AppBarLayoutParamsBean

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$ {
  ASAppBarLayoutImpl_AppBarLayoutParamsBean_initWithASAppBarLayoutImpl_(self, outer$);
  return self;
}

- (void)setLayoutScrollFlagsWithASIWidget:(id<ASIWidget>)w
                             withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *) nil_chk([((ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *) nil_chk([((ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutScrollFlagsWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (void)setLayoutScrollInterpolatorWithASIWidget:(id<ASIWidget>)w
                                    withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *) nil_chk([((ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *) nil_chk([((ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutScrollInterpolatorWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASAppBarLayoutImpl:);
  methods[1].selector = @selector(setLayoutScrollFlagsWithASIWidget:withNSString:);
  methods[2].selector = @selector(setLayoutScrollInterpolatorWithASIWidget:withNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASAppBarLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASAppBarLayoutImpl;", "setLayoutScrollFlags", "LASIWidget;LNSString;", "setLayoutScrollInterpolator" };
  static const J2ObjcClassInfo _ASAppBarLayoutImpl_AppBarLayoutParamsBean = { "AppBarLayoutParamsBean", "com.ashera.appbarlayout", ptrTable, methods, fields, 7, 0x1, 3, 1, 0, -1, -1, -1, -1 };
  return &_ASAppBarLayoutImpl_AppBarLayoutParamsBean;
}

@end

void ASAppBarLayoutImpl_AppBarLayoutParamsBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutParamsBean *self, ASAppBarLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupParamsBean_init(self);
}

ASAppBarLayoutImpl_AppBarLayoutParamsBean *new_ASAppBarLayoutImpl_AppBarLayoutParamsBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASAppBarLayoutImpl_AppBarLayoutParamsBean, initWithASAppBarLayoutImpl_, outer$)
}

ASAppBarLayoutImpl_AppBarLayoutParamsBean *create_ASAppBarLayoutImpl_AppBarLayoutParamsBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutImpl_AppBarLayoutParamsBean, initWithASAppBarLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAppBarLayoutImpl_AppBarLayoutParamsBean)

@implementation ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$ {
  ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder_initWithASAppBarLayoutImpl_(self, outer$);
  return self;
}

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutScrollFlagsWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_scrollFlags"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutScrollInterpolatorWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_scrollInterpolator"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder;", 0x1, 3, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASAppBarLayoutImpl:);
  methods[1].selector = @selector(setLayoutScrollFlagsWithNSString:);
  methods[2].selector = @selector(setLayoutScrollInterpolatorWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASAppBarLayoutImpl;", "setLayoutScrollFlags", "LNSString;", "setLayoutScrollInterpolator", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandParamsBuilder<Lcom/ashera/appbarlayout/AppBarLayoutImpl$AppBarLayoutCommandParamsBuilder;>;" };
  static const J2ObjcClassInfo _ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder = { "AppBarLayoutCommandParamsBuilder", "com.ashera.appbarlayout", ptrTable, methods, NULL, 7, 0x1, 3, 0, 0, -1, -1, 4, -1 };
  return &_ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder;
}

@end

void ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *self, ASAppBarLayoutImpl *outer$) {
  ASViewGroupImpl_ViewGroupCommandParamsBuilder_init(self);
}

ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *new_ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder, initWithASAppBarLayoutImpl_, outer$)
}

ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *create_ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder, initWithASAppBarLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder)

@implementation ASAppBarLayoutImpl_$Lambda$1

- (void)run {
  ASViewGroupImpl_nativeRemoveViewWithASIWidget_(val$widget_);
}

@end

void ASAppBarLayoutImpl_$Lambda$1_initWithASIWidget_(ASAppBarLayoutImpl_$Lambda$1 *self, id<ASIWidget> capture$0) {
  self->val$widget_ = capture$0;
  NSObject_init(self);
}

ASAppBarLayoutImpl_$Lambda$1 *new_ASAppBarLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_NEW_IMPL(ASAppBarLayoutImpl_$Lambda$1, initWithASIWidget_, capture$0)
}

ASAppBarLayoutImpl_$Lambda$1 *create_ASAppBarLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_CREATE_IMPL(ASAppBarLayoutImpl_$Lambda$1, initWithASIWidget_, capture$0)
}
