//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAppBarLayoutPlugin\src\main\java\com\ashera\appbarlayout\AppBarLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AppBarLayoutImpl")
#ifdef RESTRICT_AppBarLayoutImpl
#define INCLUDE_ALL_AppBarLayoutImpl 0
#else
#define INCLUDE_ALL_AppBarLayoutImpl 1
#endif
#undef RESTRICT_AppBarLayoutImpl

#if !defined (ASAppBarLayoutImpl_) && (INCLUDE_ALL_AppBarLayoutImpl || defined(INCLUDE_ASAppBarLayoutImpl))
#define ASAppBarLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASAppBarLayoutImpl_AppBarLayoutBean;
@class ASAppBarLayoutImpl_AppBarLayoutCommandBuilder;
@class ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder;
@class ASAppBarLayoutImpl_AppBarLayoutParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASAppBarLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASAppBarLayoutImpl_AppBarLayoutBean *)getBean;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASAppBarLayoutImpl_AppBarLayoutParamsBean *)getParamsBean;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl)

inline NSString *ASAppBarLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASAppBarLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASAppBarLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASAppBarLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASAppBarLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASAppBarLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASAppBarLayoutImpl_init(ASAppBarLayoutImpl *self);

FOUNDATION_EXPORT ASAppBarLayoutImpl *new_ASAppBarLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl *create_ASAppBarLayoutImpl_init(void);

FOUNDATION_EXPORT void ASAppBarLayoutImpl_initWithNSString_(ASAppBarLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASAppBarLayoutImpl *new_ASAppBarLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl *create_ASAppBarLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASAppBarLayoutImpl_initWithNSString_withNSString_(ASAppBarLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASAppBarLayoutImpl *new_ASAppBarLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl *create_ASAppBarLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutImpl)

@compatibility_alias ComAsheraAppbarlayoutAppBarLayoutImpl ASAppBarLayoutImpl;

#endif

#if !defined (ASAppBarLayoutImpl_Layout_scrollFlags_) && (INCLUDE_ALL_AppBarLayoutImpl || defined(INCLUDE_ASAppBarLayoutImpl_Layout_scrollFlags))
#define ASAppBarLayoutImpl_Layout_scrollFlags_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASAppBarLayoutImpl_Layout_scrollFlags : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl_Layout_scrollFlags)

FOUNDATION_EXPORT void ASAppBarLayoutImpl_Layout_scrollFlags_init(ASAppBarLayoutImpl_Layout_scrollFlags *self);

FOUNDATION_EXPORT ASAppBarLayoutImpl_Layout_scrollFlags *new_ASAppBarLayoutImpl_Layout_scrollFlags_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl_Layout_scrollFlags *create_ASAppBarLayoutImpl_Layout_scrollFlags_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutImpl_Layout_scrollFlags)

#endif

#if !defined (ASAppBarLayoutImpl_AppBarLayoutExt_) && (INCLUDE_ALL_AppBarLayoutImpl || defined(INCLUDE_ASAppBarLayoutImpl_AppBarLayoutExt))
#define ASAppBarLayoutImpl_AppBarLayoutExt_

#define RESTRICT_AppBarLayout 1
#define INCLUDE_ASAppBarLayout 1
#include "AppBarLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASAppBarLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASAppBarLayoutImpl_AppBarLayoutExt : ASAppBarLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl_AppBarLayoutExt)

FOUNDATION_EXPORT void ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutExt *self, ASAppBarLayoutImpl *outer$);

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutExt *new_ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutExt *create_ASAppBarLayoutImpl_AppBarLayoutExt_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutImpl_AppBarLayoutExt)

#endif

#if !defined (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder_) && (INCLUDE_ALL_AppBarLayoutImpl || defined(INCLUDE_ASAppBarLayoutImpl_AppBarLayoutCommandBuilder))
#define ASAppBarLayoutImpl_AppBarLayoutCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASAppBarLayoutImpl;

@interface ASAppBarLayoutImpl_AppBarLayoutCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                  withId:(id)arg1;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)addModelWithId:(id)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)endAnimator;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)invalidate;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)requestLayout;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)reset;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setExpandedWithBoolean:(jboolean)value;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)startAnimator;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetAddStatesFromChildren;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetAlpha;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetBackground;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetBackgroundTint;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetBackgroundTintMode;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetBottom;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetClickable;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetClipChildren;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetClipToPadding;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetContentDescription;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetDuplicateParentState;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetEnabled;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetFocusable;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetForeground;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetForegroundGravity;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetForegroundTint;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetForegroundTintMode;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetId;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosAccessibilityHint;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosAccessibilityValue;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosAlpha;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosBackgroundColor;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosClipsToBounds;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosContentScaleFactor;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosIsFocused;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosIsHidden;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosIsOpaque;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosLargeContentImage;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosLargeContentTitle;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosTag;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosTintColor;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetKeepScreenOn;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetLayoutDirection;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetLayoutMode;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetLeft;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetLongClickable;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetMaxHeight;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetMaxWidth;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetMinHeight;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetMinWidth;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetModelDescPath;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetModelIdPath;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetModelParam;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetModelPojoToUi;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetModelSyncEvents;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetModelUiToPojo;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetPaddingBottom;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetPaddingEnd;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetPaddingLeft;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetPaddingRight;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetPaddingStart;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetPaddingTop;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetRight;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetRotation;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetRotationX;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetRotationY;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetScaleX;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetScaleY;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetSelected;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetTextAlignment;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetTextDirection;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetTop;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetTransformPivotX;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetTransformPivotY;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetTranslationX;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetTranslationY;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetTranslationZ;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetValidateForm;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)tryGetVisibility;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                        withId:(id)arg1;

- (ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl_AppBarLayoutCommandBuilder)

FOUNDATION_EXPORT void ASAppBarLayoutImpl_AppBarLayoutCommandBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *self, ASAppBarLayoutImpl *outer$);

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *new_ASAppBarLayoutImpl_AppBarLayoutCommandBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutCommandBuilder *create_ASAppBarLayoutImpl_AppBarLayoutCommandBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutImpl_AppBarLayoutCommandBuilder)

#endif

#if !defined (ASAppBarLayoutImpl_AppBarLayoutBean_) && (INCLUDE_ALL_AppBarLayoutImpl || defined(INCLUDE_ASAppBarLayoutImpl_AppBarLayoutBean))
#define ASAppBarLayoutImpl_AppBarLayoutBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASAppBarLayoutImpl;
@protocol ASIWidget;

@interface ASAppBarLayoutImpl_AppBarLayoutBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$;

- (void)setExpandedWithBoolean:(jboolean)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl_AppBarLayoutBean)

FOUNDATION_EXPORT void ASAppBarLayoutImpl_AppBarLayoutBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutBean *self, ASAppBarLayoutImpl *outer$);

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutBean *new_ASAppBarLayoutImpl_AppBarLayoutBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutBean *create_ASAppBarLayoutImpl_AppBarLayoutBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutImpl_AppBarLayoutBean)

#endif

#if !defined (ASAppBarLayoutImpl_AppBarLayoutParamsBean_) && (INCLUDE_ALL_AppBarLayoutImpl || defined(INCLUDE_ASAppBarLayoutImpl_AppBarLayoutParamsBean))
#define ASAppBarLayoutImpl_AppBarLayoutParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASAppBarLayoutImpl;
@protocol ASIWidget;

@interface ASAppBarLayoutImpl_AppBarLayoutParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$;

- (void)setLayoutScrollFlagsWithASIWidget:(id<ASIWidget>)w
                             withNSString:(NSString *)value;

- (void)setLayoutScrollInterpolatorWithASIWidget:(id<ASIWidget>)w
                                    withNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl_AppBarLayoutParamsBean)

FOUNDATION_EXPORT void ASAppBarLayoutImpl_AppBarLayoutParamsBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutParamsBean *self, ASAppBarLayoutImpl *outer$);

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutParamsBean *new_ASAppBarLayoutImpl_AppBarLayoutParamsBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutParamsBean *create_ASAppBarLayoutImpl_AppBarLayoutParamsBean_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutImpl_AppBarLayoutParamsBean)

#endif

#if !defined (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder_) && (INCLUDE_ALL_AppBarLayoutImpl || defined(INCLUDE_ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder))
#define ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASAppBarLayoutImpl;

@interface ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASAppBarLayoutImpl:(ASAppBarLayoutImpl *)outer$;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)reset;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutScrollFlagsWithNSString:(NSString *)value;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)setLayoutScrollInterpolatorWithNSString:(NSString *)value;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder)

FOUNDATION_EXPORT void ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *self, ASAppBarLayoutImpl *outer$);

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *new_ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder *create_ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder_initWithASAppBarLayoutImpl_(ASAppBarLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASAppBarLayoutImpl_AppBarLayoutCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_AppBarLayoutImpl")
