//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAppBarLayoutPlugin\src\main\java\com\google\android\material\appbar\ViewOffsetHelper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ViewOffsetHelper")
#ifdef RESTRICT_ViewOffsetHelper
#define INCLUDE_ALL_ViewOffsetHelper 0
#else
#define INCLUDE_ALL_ViewOffsetHelper 1
#endif
#undef RESTRICT_ViewOffsetHelper

#if !defined (ASViewOffsetHelper_) && (INCLUDE_ALL_ViewOffsetHelper || defined(INCLUDE_ASViewOffsetHelper))
#define ASViewOffsetHelper_

@class ADView;

/*!
 @brief Utility helper for moving a <code>View</code> around using <code>View.offsetLeftAndRight(int)</code> and 
 <code>View.offsetTopAndBottom(int)</code>.
 <p>Also the setting of absolute offsets (similar to translationX/Y), rather than additive
  offsets.
 */
@interface ASViewOffsetHelper : NSObject

#pragma mark Public

- (instancetype)initPackagePrivateWithADView:(ADView *)view;

- (jint)getLayoutLeft;

- (jint)getLayoutTop;

- (jint)getLeftAndRightOffset;

- (jint)getTopAndBottomOffset;

- (jboolean)isHorizontalOffsetEnabled;

- (jboolean)isVerticalOffsetEnabled;

- (void)setHorizontalOffsetEnabledWithBoolean:(jboolean)horizontalOffsetEnabled;

/*!
 @brief Set the left and right offset for this <code>ViewOffsetHelper</code>'s view.
 @param offset the offset in px.
 @return true if the offset has changed
 */
- (jboolean)setLeftAndRightOffsetWithInt:(jint)offset;

/*!
 @brief Set the top and bottom offset for this <code>ViewOffsetHelper</code>'s view.
 @param offset the offset in px.
 @return true if the offset has changed
 */
- (jboolean)setTopAndBottomOffsetWithInt:(jint)offset;

- (void)setVerticalOffsetEnabledWithBoolean:(jboolean)verticalOffsetEnabled;

#pragma mark Package-Private

- (void)applyOffsets;

- (void)onViewLayout;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewOffsetHelper)

FOUNDATION_EXPORT void ASViewOffsetHelper_initPackagePrivateWithADView_(ASViewOffsetHelper *self, ADView *view);

FOUNDATION_EXPORT ASViewOffsetHelper *new_ASViewOffsetHelper_initPackagePrivateWithADView_(ADView *view) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewOffsetHelper *create_ASViewOffsetHelper_initPackagePrivateWithADView_(ADView *view);

J2OBJC_TYPE_LITERAL_HEADER(ASViewOffsetHelper)

@compatibility_alias ComGoogleAndroidMaterialAppbarViewOffsetHelper ASViewOffsetHelper;

#endif

#pragma pop_macro("INCLUDE_ALL_ViewOffsetHelper")
