//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAppBarLayoutPlugin\src\main\java\com\google\android\material\appbar\ViewOffsetBehavior.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ViewOffsetBehavior")
#ifdef RESTRICT_ViewOffsetBehavior
#define INCLUDE_ALL_ViewOffsetBehavior 0
#else
#define INCLUDE_ALL_ViewOffsetBehavior 1
#endif
#undef RESTRICT_ViewOffsetBehavior

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ASViewOffsetBehavior_) && (INCLUDE_ALL_ViewOffsetBehavior || defined(INCLUDE_ASViewOffsetBehavior))
#define ASViewOffsetBehavior_

#define RESTRICT_CoordinatorLayout 1
#define INCLUDE_ADXCoordinatorLayout_Behavior 1
#include "CoordinatorLayout.h"

@class ADView;
@class ADXCoordinatorLayout;

/*!
 @brief Behavior will automatically sets up a <code>ViewOffsetHelper</code> on a <code>View</code>.
 */
@interface ASViewOffsetBehavior : ADXCoordinatorLayout_Behavior

#pragma mark Public

- (instancetype)initPackagePrivate;

- (jint)getLeftAndRightOffset;

- (jint)getTopAndBottomOffset;

- (jboolean)isHorizontalOffsetEnabled;

- (jboolean)isVerticalOffsetEnabled;

- (jboolean)onLayoutChildWithADXCoordinatorLayout:(ADXCoordinatorLayout *)parent
                                       withADView:(ADView *)child
                                          withInt:(jint)layoutDirection;

- (void)setHorizontalOffsetEnabledWithBoolean:(jboolean)horizontalOffsetEnabled;

- (jboolean)setLeftAndRightOffsetWithInt:(jint)offset;

- (jboolean)setTopAndBottomOffsetWithInt:(jint)offset;

- (void)setVerticalOffsetEnabledWithBoolean:(jboolean)verticalOffsetEnabled;

#pragma mark Protected

- (void)layoutChildWithADXCoordinatorLayout:(ADXCoordinatorLayout *)parent
                                 withADView:(ADView *)child
                                    withInt:(jint)layoutDirection;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewOffsetBehavior)

FOUNDATION_EXPORT void ASViewOffsetBehavior_initPackagePrivate(ASViewOffsetBehavior *self);

FOUNDATION_EXPORT ASViewOffsetBehavior *new_ASViewOffsetBehavior_initPackagePrivate(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewOffsetBehavior *create_ASViewOffsetBehavior_initPackagePrivate(void);

J2OBJC_TYPE_LITERAL_HEADER(ASViewOffsetBehavior)

@compatibility_alias ComGoogleAndroidMaterialAppbarViewOffsetBehavior ASViewOffsetBehavior;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ViewOffsetBehavior")
